# -*- coding: utf-8 -*-
"""05.04.01 Exercícios if.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JjcqciIJtjIfCFgoiGJIHEAwsVXTME1Z

# Exercícios com if

## 1. Cálculo de Bônus

- Crie um programa que calcule e dê um print no bônus que os funcionários devem receber segundo a regra:

A meta é 1000 vendas.<br> 
Se o valor de vendas for maior ou igual a meta, o valor do bônus do funcionário é 10% do valor de vendas.<br>
Caso contrário o valor de bônus do funcionário é 0.<br>
Print o bônus dos 3 funcionários
"""
meta = 1000
vendas_funcionario1 = 1000
vendas_funcionario2 = 770
vendas_funcionario3 = 2700

escolha_funcionario = input('você é qual funcionário (escreva 1, 2 ou 3)?')

#crie seu código aqui
if escolha_funcionario == '1':
    if vendas_funcionario1 >= meta:
            bonus_funcionario1 = 0.10 * vendas_funcionario1
            print (f'O funcionário 1 ganhou {bonus_funcionario1} de bônus.')
    else: print(f'Você não ganhou bônus.')
elif escolha_funcionario == '2':
    if vendas_funcionario2 >= meta:
         bonus_funcionario2 = 0.10 * vendas_funcionario1
         print (f'O funcionário 2 ganhou {bonus_funcionario2} de bônus.')
    else: print(f'Você não ganhou bônus.')
elif escolha_funcionario == '3':
    if vendas_funcionario3 >= meta:
         bonus_funcionario3 = 0.10 * vendas_funcionario3
         print (f'O funcionário 3 ganhou {bonus_funcionario3} de bônus.')
    else: print(f'Você não ganhou bônus.')
else: print(f'Você escolheu um funcionário inexistente.')
"""Resposta:
O funcionário 1 ganhou 100 de bônus
O funcionário 2 ganhou 0 de bônus
O funcionário 3 ganhou 270 de bônus

## 2. Cálculo de bônus com uma nova regra

- Agora, crie um novo código que calcule e dê um print no bônus dos funcionários novamente. Porém há uma nova regra nesse 2º caso:

A meta é 1000 vendas<br>
Agora, os funcionários que venderem muito acima da meta ganham mais bônus do que os outros. Então o bônus é definido da seguinte forma:<br>

- Se vendas funcionário for maior ou igual a 2000, então o bônus é de 15% sobre o valor de vendas
- Se vendas funcionário for menor do que 2000 e maior ou igual a 1000, então o bônus é de 10% sobre o valor de vendas
- Se vendas funcionário for menos do que 1000 então o bônus do funcionário é de 0.

Use as mesmas variáveis de vendas_funcionários
"""

#crie seu código aqui
#obs: há 2 formas de fazer, com if dentro de if ou então com if e elif. Escolha a que você preferir
if escolha_funcionario == '1':
    if vendas_funcionario1 >= (meta * 2):
            bonus_funcionario1 = 0.15 * vendas_funcionario1
            print (f'O funcionário 1 ganhou {bonus_funcionario1} de bônus.')
    elif (meta * 2) > vendas_funcionario1 >= (meta):
            bonus_funcionario1 = 0.15 * vendas_funcionario1
            print (f'O funcionário 1 ganhou {bonus_funcionario1} de bônus.')
    else: print(f'Você não ganhou bônus.')
elif escolha_funcionario == '2':
    if vendas_funcionario2 >= (meta * 2):
            bonus_funcionario2 = 0.15 * vendas_funcionario2
            print (f'O funcionário 2 ganhou {bonus_funcionario2} de bônus.')
    elif (meta * 2) > vendas_funcionario2 >= (meta):
            bonus_funcionario2 = 0.15 * vendas_funcionario2
            print (f'O funcionário 2 ganhou {bonus_funcionario2} de bônus.')
    else: print(f'Você não ganhou bônus.')
elif escolha_funcionario == '3':
    if vendas_funcionario3 >= (meta * 2):
            bonus_funcionario3 = 0.15 * vendas_funcionario3
            print (f'O funcionário 3 ganhou {bonus_funcionario3} de bônus.')
    elif (meta * 2) > vendas_funcionario3 >= (meta):
            bonus_funcionario3 = 0.15 * vendas_funcionario3
            print (f'O funcionário 3 ganhou {bonus_funcionario3} de bônus.')
    else: print(f'Você não ganhou bônus.')
else: print(f'Você escolheu um funcionário inexistente.')
"""Resposta:
O funcionário 1 ganhou 100 de bônus
O funcionário 2 ganhou 0 de bônus
O funcionário 3 ganhou 405 de bônus
"""